name: changepoint_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.*
  - pandas=1.3.*
  - matplotlib=3.4.*
  - scipy=1.7.*
  - ruptures=1.1.*
  - pip
  - pip:
    - ruptures==1.1.5  # Specify the exact version if needed
